// S21: A reader that converts all Unicode letter mapped to their upper case.
//
//     $ echo "Hello Gophers" | go run main.go
//     HELLO GOPHERS
package main

import (
	"io"
	"log"
	"os"
)

// TODO: Implement UpperReader, a reader that converts all Unicode letter mapped to their upper case. 11 lines.
// ...
// ...
// ...

// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
func main() {
	_, err := io.Copy(os.Stdout, &UpperReader{r: os.Stdin})
	if err != nil {
		log.Fatal(err)
	}
}
