// S04: Decompression with gzip and a simple filter chain.
//
// OUTPUT:
//
//     $ cat hello.txt.gz | go run main.go
//     Don't just check errors, handle them gracefully.
package main

func main() {

	// TODO: Read gzip compressed data from standard input and write
	//       to standard output, without using a byte slice (7 lines).
	//
	// ...
	// ...
	// ...
	// ...
	// ...
	// ...
	// ...
}
