// S04: Decompression with gzip and a simple filter chain.
//
// OUTPUT:
//
//     $ cat hello.txt.gz | go run main.go
//     Don't just check errors, handle them gracefully.
package main

func main() {
	// TODO: Read gzip compressed input from standard input and print it to standard output,
	// TODO: without using a byte slice (7 lines).
	// ...
	// ...
	// ...
	// ...
	// ...
	// ...
	// ...
}
